const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={topic:'',platform:'Instagram Reels',ratio:'9:16',objective:'Viralizar',duration:'auto',presence:'100% IA',ideas:[],validated:false,selected:null,renderUrl:null,history:JSON.parse(localStorage.getItem('aureonV30History')||'[]')};
const formats=['Lista rápida','Antes e depois','POV','Storytelling','Mito ou verdade','Erro comum','Desafio','Comparação','Tutorial relâmpago','Bastidores','Opinião forte','Caso real','3 sinais','Checklist','Reação','Pergunta provocativa','Transformação','Segredo pouco falado','Ranking','Teste em tempo real','Explicação visual','Mini documentário','Problema → solução','Contraste','Trend adaptada','Demo','Quebra de objeção','Prova social','Micro aula','Convite direto'];
const angleTemplates=[
 t=>`3 coisas sobre ${t} que quase ninguém percebe`,t=>`O erro em ${t} que faz você perder tempo`,t=>`POV: você descobre um jeito melhor de lidar com ${t}`,t=>`${t}: antes de fazer isso, veja estes 3 pontos`,t=>`O que ninguém te conta sobre ${t}`,t=>`Se eu começasse hoje em ${t}, faria isso primeiro`,t=>`Pare de fazer isso em ${t}`,t=>`A diferença entre quem entende ${t} e quem só tenta`,t=>`Como melhorar ${t} em menos de 1 minuto`,t=>`Bastidores: como ${t} realmente funciona`,t=>`Uma opinião impopular sobre ${t}`,t=>`O caso que mudou minha visão sobre ${t}`,t=>`3 sinais de que você precisa mudar algo em ${t}`,t=>`Checklist rápido para acertar em ${t}`,t=>`Reagindo ao maior erro que vejo em ${t}`,t=>`Você faria isso com ${t}?`,t=>`De comum para incrível: transformação em ${t}`,t=>`O segredo mais simples para evoluir em ${t}`,t=>`Top 5 formas de melhorar ${t}`,t=>`Testando uma ideia de ${t} na prática`,t=>`${t} explicado visualmente em 30 segundos`,t=>`A história por trás de ${t} que vale conhecer`,t=>`Seu problema com ${t} pode ter esta solução`,t=>`${t}: jeito antigo vs. jeito inteligente`,t=>`Uma trend que faz sentido para ${t}`,t=>`Veja ${t} funcionando na prática`,t=>`“Isso não funciona em ${t}” — será?`,t=>`Por que pessoas escolhem isso em ${t}`,t=>`Aprenda uma coisa útil sobre ${t} agora`,t=>`Se ${t} importa para você, faça isso hoje`];
const hooks=[
 'Você provavelmente está fazendo isso do jeito mais difícil.',
 'Se eu tivesse só 30 segundos para te mostrar isso, começaria aqui.',
 'Quase ninguém percebe este detalhe — e ele muda tudo.',
 'Antes de continuar rolando, olha isso.',
 'Isso parece simples. O impacto não é.',
 'O erro não está onde você imagina.',
 'Tem um jeito muito mais inteligente de fazer isso.',
 'Se você trabalha com isso, precisa ver até o final.'
];
const objectives={
 'Viralizar':{cta:'Salva este vídeo e manda para alguém que precisa ver isso.',weight:{hook:5,retention:6,share:6,sales:0,clarity:1}},
 'Vender':{cta:'Quer aplicar isso no seu negócio? Chama no direct.',weight:{hook:3,retention:3,share:1,sales:7,clarity:3}},
 'Educar':{cta:'Salva para rever depois e segue para aprender mais.',weight:{hook:2,retention:3,share:2,sales:0,clarity:7}},
 'Atrair seguidores':{cta:'Segue agora porque o próximo vídeo continua daqui.',weight:{hook:4,retention:5,share:3,sales:0,clarity:2}},
 'Apresentar produto':{cta:'Se isso faz sentido para você, conheça a solução completa.',weight:{hook:2,retention:3,share:1,sales:6,clarity:4}},
 'Gerar autoridade':{cta:'Se você quer aprofundar este tema, acompanha os próximos conteúdos.',weight:{hook:2,retention:3,share:2,sales:1,clarity:6}}
};
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function seeded(seed,min,max){const x=Math.sin(seed)*10000;const n=x-Math.floor(x);return Math.floor(min+n*(max-min+1))}
function recommendedDuration(){if(state.duration!=='auto')return +state.duration;if(state.platform==='Instagram Stories')return 15;if(state.platform==='Anúncio')return 15;if(state.objective==='Educar')return 45;if(state.objective==='Apresentar produto'||state.objective==='Vender')return 30;return 30}
function updateDurationHint(){const d=recommendedDuration();$('#durationHint').textContent=`Recomendação: ${d}s para ${state.platform} com foco em ${state.objective.toLowerCase()}.`}
function makeIdea(i){const seed=hash(`${state.topic}|${state.platform}|${state.objective}|${i}`);const title=angleTemplates[i](state.topic);const format=formats[i];const hook=hooks[seed%hooks.length];const base={hook:seeded(seed+1,13,20),retention:seeded(seed+2,12,20),share:seeded(seed+3,10,20),clarity:seeded(seed+4,12,20),sales:seeded(seed+5,8,20),ease:seeded(seed+6,7,10)};const w=objectives[state.objective].weight;let score=Math.round((base.hook+base.retention+base.share+base.clarity+base.sales)/1.0/100*88+base.ease*.9+(w.hook+w.retention+w.share+w.sales+w.clarity)*.22);score=Math.max(61,Math.min(98,score));const concept=`${format} sobre ${state.topic}, construído para ${state.objective.toLowerCase()} em ${state.platform}. Abre com tensão, entrega valor rápido e termina com uma ação clara.`;return{id:i+1,title,format,hook,concept,score,metrics:base,cta:objectives[state.objective].cta}}
function saveHistory(){const item={topic:state.topic,platform:state.platform,objective:state.objective,date:new Date().toLocaleString('pt-BR')};state.history=[item,...state.history.filter(x=>!(x.topic===item.topic&&x.platform===item.platform))].slice(0,12);localStorage.setItem('aureonV30History',JSON.stringify(state.history));renderHistoryCount()}
function renderHistoryCount(){$('#historyCount').textContent=state.history.length}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.classList.remove('show'),2400)}
function generateIdeas(){const topic=$('#topicInput').value.trim();if(!topic){showToast('Digite uma palavra, produto ou tema.');$('#topicInput').focus();return}state.topic=topic.toUpperCase();state.validated=false;state.selected=null;state.ideas=Array.from({length:30},(_,i)=>makeIdea(i));saveHistory();$('#topicTitle').textContent=state.topic;$('#validateBtn').textContent='VALIDAR AS 30 ↗';$('#winnerCard').classList.add('hidden');$('#ideasSection').classList.remove('hidden');$('#studioSection').classList.add('hidden');renderIdeas();setTimeout(()=>$('#ideasSection').scrollIntoView({behavior:'smooth'}),80)}
function renderIdeas(filter='all'){let ideas=[...state.ideas];const sort=$('#sortSelect').value;if(state.validated){if(sort==='score')ideas.sort((a,b)=>b.score-a.score);if(sort==='hook')ideas.sort((a,b)=>b.metrics.hook-a.metrics.hook);if(sort==='retention')ideas.sort((a,b)=>b.metrics.retention-a.metrics.retention)}if(filter==='top10'&&state.validated)ideas=ideas.sort((a,b)=>b.score-a.score).slice(0,10);if(filter==='fast'&&state.validated)ideas=ideas.filter(i=>i.metrics.retention>=17);if(filter==='sales'&&state.validated)ideas=ideas.filter(i=>i.metrics.sales>=17);$('#ideasGrid').innerHTML=ideas.map(i=>`<article class="idea-card"><div class="idea-top"><span>#${String(i.id).padStart(2,'0')}</span>${state.validated?`<span class="score-pill">${i.score}/100</span>`:`<span class="pending-pill">A VALIDAR</span>`}</div><h3>${i.title}</h3><p>${i.concept}</p><div class="idea-foot"><span>${i.format}</span><button data-idea="${i.id}">VER IDEIA →</button></div></article>`).join('');$$('[data-idea]').forEach(b=>b.onclick=()=>openIdea(+b.dataset.idea))}
function validateIdeas(){if(!state.ideas.length)return;state.validated=true;state.ideas.sort((a,b)=>b.score-a.score);state.ideas.forEach((i,idx)=>i.rank=idx+1);$('#validateBtn').textContent='VALIDAÇÃO CONCLUÍDA';$('#sortSelect').value='score';renderWinner();renderIdeas('all');showToast('30 ideias analisadas. Melhor oportunidade encontrada.')}
function renderWinner(){const w=state.ideas[0], card=$('#winnerCard');card.classList.remove('hidden');card.innerHTML=`<div><div class="winner-label">🏆 MELHOR OPORTUNIDADE</div><h3>${w.title}</h3><p>${w.concept}</p><div class="metric-row" style="margin-top:14px"><span class="metric good">Hook ${w.metrics.hook}/20</span><span class="metric good">Retenção ${w.metrics.retention}/20</span><span class="metric">Compart. ${w.metrics.share}/20</span><span class="metric">Comercial ${w.metrics.sales}/20</span></div></div><div><div class="winner-score">${w.score}/100</div><button class="primary-btn" id="winnerCreate">CRIAR ESTE VÍDEO →</button></div>`;$('#winnerCreate').onclick=()=>openStudio(w.id)}
function openIdea(id){const i=state.ideas.find(x=>x.id===id),m=$('#ideaModal');$('#ideaModalBody').innerHTML=`<div class="eyebrow">CONCEITO #${String(i.id).padStart(2,'0')}</div><h3>${i.title}</h3><p>${i.concept}</p><div class="idea-detail-grid"><div class="detail-box"><label>HOOK</label><p>${i.hook}</p></div><div class="detail-box"><label>FORMATO</label><p>${i.format}</p></div><div class="detail-box"><label>PLATAFORMA</label><p>${state.platform}</p></div><div class="detail-box"><label>OBJETIVO</label><p>${state.objective}</p></div></div>${state.validated?`<div class="metric-row"><span class="metric good">Score ${i.score}/100</span><span class="metric">Hook ${i.metrics.hook}/20</span><span class="metric">Retenção ${i.metrics.retention}/20</span><span class="metric">Compart. ${i.metrics.share}/20</span><span class="metric">Clareza ${i.metrics.clarity}/20</span><span class="metric">Comercial ${i.metrics.sales}/20</span></div>`:''}<div class="modal-actions"><button class="primary-btn" id="modalCreate">CRIAR ROTEIRO E VÍDEO →</button></div>`;m.classList.remove('hidden');$('#modalCreate').onclick=()=>{m.classList.add('hidden');openStudio(id)}}
function buildStoryboard(i){const d=recommendedDuration(),n=d<=15?4:5,part=d/n;const middle=[`Mostre o problema em ${state.topic} de forma visual e rápida.`,`Entregue a principal virada: ${i.title}.`,`Demonstre uma aplicação prática ou contraste antes/depois.`];const scenes=[{title:'HOOK',text:i.hook,visual:`Abertura forte, movimento de câmera e texto grande: “${i.title}”`},{title:'PROBLEMA',text:`A maioria das pessoas olha para ${state.topic} do jeito óbvio — e perde a parte que realmente importa.`,visual:`Cena de contraste mostrando o jeito comum vs. o problema real.`},{title:'VIRADA',text:`A mudança acontece quando você transforma ${state.topic} em uma decisão simples, visual e prática.`,visual:`Transição rápida, destaque de 3 pontos e animação de progresso.`},{title:'PROVA',text:`É isso que faz esta abordagem funcionar: clareza, velocidade e uma próxima ação objetiva.`,visual:`Demonstração, resultado ou comparação lado a lado.`},{title:'CTA',text:i.cta,visual:`Tela limpa com CTA grande e assinatura AUREON V30.`}].slice(0,n);return scenes.map((s,idx)=>({...s,start:Math.round(idx*part),end:Math.round((idx+1)*part)}))}
function narrationFromScenes(scenes){return scenes.map(s=>s.text).join(' ')}
function postCaptionFor(i){return `${i.title}\n\n${i.hook}\n\nConteúdo criado para ${state.platform} com foco em ${state.objective.toLowerCase()}.\n\n${i.cta}\n\n#${state.topic.replace(/[^A-Z0-9]/g,'')} #conteudo #video #aureonv30`}
function openStudio(id){const i=state.ideas.find(x=>x.id===id);state.selected=i;state.renderUrl&&URL.revokeObjectURL(state.renderUrl);state.renderUrl=null;$('#downloadBtn').disabled=true;$('#ideasSection').classList.add('hidden');$('#studioSection').classList.remove('hidden');$('#studioRank').textContent=state.validated?`#${String(i.rank||i.id).padStart(2,'0')}`:`#${String(i.id).padStart(2,'0')}`;$('#studioScore').textContent=state.validated?`${i.score}/100`:'NÃO VALIDADO';$('#studioTitle').textContent=i.title;$('#studioConcept').textContent=i.concept;$('#studioMetrics').innerHTML=`<span class="metric good">${state.platform}</span><span class="metric">${recommendedDuration()}s</span><span class="metric">${state.objective}</span><span class="metric">${state.presence}</span>`;const scenes=buildStoryboard(i),n=narrationFromScenes(scenes);$('#scriptHook').textContent=i.hook;$('#scriptNarration').textContent=n;$('#scriptCta').textContent=i.cta;$('#storyboardTitle').textContent=`${scenes.length} cenas · ${recommendedDuration()} segundos`;$('#storyboard').innerHTML=scenes.map((s,idx)=>`<article class="scene"><span class="time">${String(s.start).padStart(2,'0')}s — ${String(s.end).padStart(2,'0')}s</span><b>${String(idx+1).padStart(2,'0')} · ${s.title}</b><p>${s.text}</p><small>${s.visual}</small></article>`).join('');$('#postCaption').textContent=postCaptionFor(i);setupCanvas();drawFrame(0,scenes,i,recommendedDuration());setTimeout(()=>$('#studioSection').scrollIntoView({behavior:'smooth'}),80)}
function setupCanvas(){const c=$('#videoCanvas'),shell=$('#canvasShell');if(state.ratio==='16:9'){c.width=1280;c.height=720;shell.classList.remove('vertical');shell.classList.add('horizontal');$('#formatBadge').textContent='1280 × 720 · 16:9'}else{c.width=720;c.height=1280;shell.classList.remove('horizontal');shell.classList.add('vertical');$('#formatBadge').textContent='720 × 1280 · 9:16'}}
function wrapText(ctx,text,maxWidth,fontSize){ctx.font=`800 ${fontSize}px Inter,Arial,sans-serif`;const words=text.split(' '),lines=[];let line='';for(const word of words){const test=(line+' '+word).trim();if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines.slice(0,5)}
function drawFrame(t,scenes,i,total){const c=$('#videoCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height,sceneIndex=Math.min(scenes.length-1,Math.floor(t/total*scenes.length)),s=scenes[sceneIndex],local=(t-(sceneIndex*total/scenes.length))/(total/scenes.length),pulse=(Math.sin(t*2.4)+1)/2;const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#090d1a');g.addColorStop(.5,'#16133a');g.addColorStop(1,'#063b38');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.16;for(let k=0;k<14;k++){const x=(w*((k*89%101)/101)+Math.sin(t*.45+k)*34)%w,y=(h*((k*53%97)/97)+Math.cos(t*.38+k)*44)%h,r=12+(k%5)*9+pulse*7;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=k%2?'#7c5cff':'#4ee6d4';ctx.fill()}ctx.globalAlpha=1;const pad=w*.075;ctx.fillStyle='#8f7cff';ctx.font=`800 ${Math.round(w*.024)}px Inter,Arial`;ctx.fillText(`AUREON V30 · ${state.platform.toUpperCase()}`,pad,h*.08);ctx.fillStyle='#6de8d3';ctx.font=`900 ${Math.round(w*.022)}px Inter,Arial`;ctx.fillText(`${s.title} · ${Math.max(0,Math.ceil(total-t))}s`,pad,h*.13);const fs=state.ratio==='9:16'?Math.round(w*.082):Math.round(w*.05),lines=wrapText(ctx,s.text,w-pad*2,fs),lineH=fs*1.08;ctx.fillStyle='#f5f7ff';ctx.textBaseline='middle';let y=h*.45-lines.length*lineH/2;lines.forEach((line,idx)=>{ctx.globalAlpha=Math.min(1,.35+local*1.8);ctx.fillText(line,pad,y+idx*lineH)});ctx.globalAlpha=1;ctx.fillStyle='rgba(255,255,255,.10)';ctx.fillRect(pad,h*.82,w-pad*2,2);ctx.fillStyle='#fff';ctx.font=`600 ${Math.round(w*.026)}px Inter,Arial`;const sub=wrapText(ctx,s.visual,w-pad*2,Math.round(w*.026));sub.slice(0,2).forEach((line,idx)=>ctx.fillText(line,pad,h*.865+idx*w*.034));ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(0,h-8,w,8);ctx.fillStyle='#4ee6d4';ctx.fillRect(0,h-8,w*Math.min(1,t/total),8)}
async function playPreview(){if(!state.selected)return;$('#previewBtn').classList.add('hidden');const scenes=buildStoryboard(state.selected),total=recommendedDuration(),previewLength=Math.min(8,total),start=performance.now();$('#renderState').textContent='Preview em execução';function tick(now){const elapsed=(now-start)/1000,sim=elapsed/previewLength*total;drawFrame(sim,scenes,state.selected,total);$('#timelineProgress').style.width=`${Math.min(100,elapsed/previewLength*100)}%`;if(elapsed<previewLength)requestAnimationFrame(tick);else{$('#renderState').textContent='Preview concluído';$('#previewBtn').classList.remove('hidden');$('#timelineProgress').style.width='0%'}}requestAnimationFrame(tick)}
function chooseMime(){const list=['video/mp4;codecs=avc1.42E01E','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'];return list.find(m=>window.MediaRecorder&&MediaRecorder.isTypeSupported(m))||''}
async function renderVideo(){if(!state.selected)return;if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){showToast('Seu navegador não suporta renderização local de vídeo. Use Chrome ou Edge atualizado.');return}const total=recommendedDuration();if(total>60){showToast('Nesta versão, a renderização completa está otimizada para vídeos de até 60s.');return}const btn=$('#renderBtn'),c=$('#videoCanvas'),scenes=buildStoryboard(state.selected),stream=c.captureStream(30),mime=chooseMime(),chunks=[];btn.disabled=true;$('#downloadBtn').disabled=true;$('#previewBtn').classList.add('hidden');$('#renderState').textContent=`Criando vídeo de ${total}s...`;const rec=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:5000000}:undefined);rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:mime||'video/webm'});state.renderUrl&&URL.revokeObjectURL(state.renderUrl);state.renderUrl=URL.createObjectURL(blob);const dl=$('#downloadBtn');dl.disabled=false;dl.dataset.ext=(mime||'').includes('mp4')?'mp4':'webm';btn.disabled=false;$('#previewBtn').classList.remove('hidden');$('#renderState').textContent='Vídeo criado com sucesso';$('#timelineProgress').style.width='100%';showToast('Vídeo criado. Agora você pode baixar.')};rec.start(250);const start=performance.now();function tick(now){const elapsed=(now-start)/1000;drawFrame(Math.min(elapsed,total),scenes,state.selected,total);$('#timelineProgress').style.width=`${Math.min(100,elapsed/total*100)}%`;if(elapsed<total)requestAnimationFrame(tick);else setTimeout(()=>rec.state!=='inactive'&&rec.stop(),120)}requestAnimationFrame(tick)}
function downloadVideo(){if(!state.renderUrl)return;const a=document.createElement('a');a.href=state.renderUrl;a.download=`AUREON-V30-${state.topic.replace(/\s+/g,'-')}.${$('#downloadBtn').dataset.ext||'webm'}`;document.body.appendChild(a);a.click();a.remove()}
function speakNarration(){if(!('speechSynthesis'in window)||!state.selected){showToast('Narração do sistema não disponível neste navegador.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('#scriptNarration').textContent);u.lang='pt-BR';u.rate=1.03;speechSynthesis.speak(u)}
function copyText(text,msg){navigator.clipboard?.writeText(text).then(()=>showToast(msg)).catch(()=>showToast('Não foi possível copiar automaticamente.'))}
function renderHistory(){const list=$('#historyList');list.innerHTML=state.history.length?state.history.map((h,idx)=>`<div class="history-item"><div><b>${h.topic}</b><span>${h.platform} · ${h.objective} · ${h.date}</span></div><button data-history="${idx}">ABRIR</button></div>`).join(''):'<p>Nenhuma exploração ainda.</p>';$$('[data-history]').forEach(b=>b.onclick=()=>{const h=state.history[+b.dataset.history];$('#topicInput').value=h.topic;state.platform=h.platform;state.objective=h.objective;$('#historyModal').classList.add('hidden');generateIdeas()})}
function bind(){renderHistoryCount();updateDurationHint();$$('.platform').forEach(b=>b.onclick=()=>{$$('.platform').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.platform=b.dataset.platform;state.ratio=b.dataset.ratio;updateDurationHint()});$$('#objectiveSet .chip').forEach(b=>b.onclick=()=>{$$('#objectiveSet .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.objective=b.dataset.value;updateDurationHint()});$$('#durationSet .chip').forEach(b=>b.onclick=()=>{$$('#durationSet .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.duration=b.dataset.value;updateDurationHint()});$$('.presence').forEach(b=>b.onclick=()=>{$$('.presence').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.presence=b.dataset.value});$$('[data-topic]').forEach(b=>b.onclick=()=>{$('#topicInput').value=b.dataset.topic;$('#topicInput').focus()});$('#generateBtn').onclick=generateIdeas;$('#topicInput').addEventListener('keydown',e=>{if(e.key==='Enter')generateIdeas()});$('#validateBtn').onclick=validateIdeas;$('#newSearchBtn').onclick=()=>{$('#setupSection').scrollIntoView({behavior:'smooth'});$('#topicInput').focus()};$('#sortSelect').onchange=()=>renderIdeas($('.filter.active').dataset.filter);$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderIdeas(b.dataset.filter)});$('#backIdeasBtn').onclick=()=>{$('#studioSection').classList.add('hidden');$('#ideasSection').classList.remove('hidden');$('#ideasSection').scrollIntoView({behavior:'smooth'})};$('#previewBtn').onclick=playPreview;$('#renderBtn').onclick=renderVideo;$('#downloadBtn').onclick=downloadVideo;$('#speakBtn').onclick=speakNarration;$('#copyScriptBtn').onclick=()=>copyText(`HOOK\n${$('#scriptHook').textContent}\n\nNARRAÇÃO\n${$('#scriptNarration').textContent}\n\nCTA\n${$('#scriptCta').textContent}`,'Roteiro copiado.');$('#copyCaptionBtn').onclick=()=>copyText($('#postCaption').textContent,'Legenda copiada.');$('#historyBtn').onclick=()=>{renderHistory();$('#historyModal').classList.remove('hidden')};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.add('hidden'));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}))}
bind();