import { parseBrief } from './modules/blueprint.js';
import { generateProject } from './modules/project-generator.js';
import { applyMutation } from './modules/mutations.js';
import { saveProject, loadProjects } from './modules/storage.js';
import { serializeProject } from './modules/export.js';
import { renderPreview } from './modules/preview.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let blueprint=null, project=null, activeScreen=null;
const views=['#startView','#blueprintView','#builderView'];
function showView(id){views.forEach(v=>$(v).classList.toggle('hidden',v!==id));window.scrollTo({top:0,behavior:'smooth'})}
function showError(target,msg=''){const n=$(target);n.textContent=msg;n.classList.toggle('hidden',!msg)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function featureLabel(x){return ({dashboard:'Dashboard',expenses:'Gastos',debts:'Dívidas',clients:'Clientes',leads:'Leads',pipeline:'Pipeline',catalog:'Catálogo',cart:'Carrinho',orders:'Pedidos',calendar:'Calendário',tasks:'Tarefas',ranking:'Ranking',notifications:'Notificações',reports:'Relatórios','cloud-data':'Dados em nuvem'})[x]||x}
function renderRecent(){const mount=$('#recentProjects');mount.replaceChildren();let items=[];try{items=loadProjects(localStorage)}catch{showError('#startError','O navegador bloqueou o armazenamento. Você ainda pode criar um projeto, mas ele não será salvo.')}if(!items.length){const e=document.createElement('div');e.className='empty-recent';e.textContent='Nenhum projeto salvo ainda. Seu próximo app começa acima.';mount.append(e);return}items.slice(0,6).forEach(p=>{const b=document.createElement('button');b.className='recent-card';const cat=document.createElement('span');cat.textContent=String(p.category||'APP').toUpperCase();const name=document.createElement('b');name.textContent=p.name;const d=document.createElement('small');d.textContent=`${p.screens.length} telas • ${p.entities.length} entidades`;b.append(cat,name,d);b.onclick=()=>openProject(p);mount.append(b)})}
function presentBlueprint(bp){blueprint=bp;$('#blueprintCategory').textContent=bp.category.toUpperCase();$('#blueprintName').textContent=bp.name;$('#blueprintSummary').textContent=bp.description;const f=$('#blueprintFeatures');f.replaceChildren();(bp.features.length?bp.features:['estrutura-base','navegação','PWA']).forEach(x=>{const s=document.createElement('span');s.className='tag';s.textContent=featureLabel(x);f.append(s)});const sc=$('#blueprintScreens');sc.replaceChildren();bp.screens.forEach(x=>{const n=document.createElement('div');n.className='stack-item';n.textContent=x;sc.append(n)});const data=$('#blueprintData');data.replaceChildren();(bp.entities.length?bp.entities:['users','records']).forEach(x=>{const n=document.createElement('div');n.className='stack-item';n.textContent=x;data.append(n)});$('#blueprintStack').textContent=`${bp.stack} • ${bp.integrations.length?bp.integrations.join(' • '):'sem integração externa obrigatória'}`;showView('#blueprintView')}
function buildFromBrief(){const brief=$('#briefInput').value.trim();if(!brief){showError('#startError','Descreva o aplicativo que você quer criar.');$('#briefInput').focus();return}showError('#startError');presentBlueprint(parseBrief(brief))}
function addChat(kind,text){const n=document.createElement('div');n.className=`bubble ${kind}`;n.textContent=text;$('#chatHistory').append(n);$('#chatHistory').scrollTop=$('#chatHistory').scrollHeight}
function renderPanels(){const files=$('#filesPanel');files.replaceChildren();project.files.forEach(f=>{const n=document.createElement('div');n.className='tree-row';const b=document.createElement('b');b.textContent=f.path;const s=document.createElement('small');s.textContent=f.language;n.append(b,s);files.append(n)});const screens=$('#screensPanel');screens.replaceChildren();project.screens.forEach(s=>{const n=document.createElement('div');n.className=`screen-row ${s.id===activeScreen?'active':''}`;n.textContent=s.name;n.onclick=()=>{activeScreen=s.id;renderWorkspace()};screens.append(n)});const data=$('#dataPanel');data.replaceChildren();project.entities.forEach(e=>{const n=document.createElement('div');n.className='entity-row';const b=document.createElement('b');b.textContent=e.name;const s=document.createElement('small');s.textContent=(e.fields||[]).join(' • ');n.append(b,s);data.append(n)});if(!project.entities.length){const n=document.createElement('div');n.className='entity-row';n.textContent='Nenhuma entidade definida.';data.append(n)}const st=$('#settingsPanel');st.replaceChildren();[['Categoria',project.category],['Estilo',project.style],['Stack',project.stack],['Integrações',project.integrations.join(', ')||'Nenhuma']].forEach(([a,b])=>{const n=document.createElement('div');n.className='settings-row';const k=document.createElement('b');k.textContent=a;const v=document.createElement('small');v.textContent=b;n.append(k,v);st.append(n)})}
function renderWorkspace(){if(!project)return;$('#projectName').textContent=project.name;$('#projectCategory').textContent=project.category.toUpperCase();if(!activeScreen||!project.screens.some(s=>s.id===activeScreen))activeScreen=project.screens[0]?.id;try{const selected=renderPreview(project,$('#previewMount'),activeScreen);activeScreen=selected||activeScreen;const screen=project.screens.find(s=>s.id===activeScreen);$('#activeScreenLabel').textContent=screen?.name||'Preview';showError('#builderError')}catch(e){showError('#builderError',`Não foi possível renderizar o preview. ${e.message}`)}renderPanels();$$('[data-preview-screen]').forEach(b=>b.onclick=()=>{activeScreen=b.dataset.previewScreen;renderWorkspace()});$('#projectStatus').textContent='Em edição'}
function openProject(p){project=structuredClone(p);activeScreen=project.screens[0]?.id;$('#chatHistory').replaceChildren();addChat('ai',`Projeto “${project.name}” aberto. Peça uma alteração e eu atualizo a estrutura.`);renderWorkspace();showView('#builderView');setMobilePanel('preview')}
function confirmBuild(){if(!blueprint)return;project=generateProject(blueprint);activeScreen=project.screens[0]?.id;$('#chatHistory').replaceChildren();addChat('ai',`Criei ${project.name} com ${project.screens.length} telas. Você pode pedir ranking, relatórios, login Google, Supabase, notificações ou um visual mais futurista.`);try{saveProject(localStorage,project);$('#projectStatus').textContent='Salvo'}catch{showError('#builderError','O projeto foi criado, mas não consegui salvar neste navegador. Você pode continuar trabalhando e exportar o projeto.')}renderWorkspace();showView('#builderView');setMobilePanel('preview')}
function sendChat(message){const msg=(message||$('#chatInput').value).trim();if(!msg)return;addChat('user',msg);$('#chatInput').value='';const result=applyMutation(project,msg);if(!result.supported){addChat('ai',result.summary);return}project=result.project;activeScreen=project.screens.find(s=>['ranking','reports'].includes(s.type)&&msg.toLowerCase().includes(s.type==='ranking'?'ranking':'relat'))?.id||activeScreen;addChat('ai',result.summary);try{saveProject(localStorage,project);$('#projectStatus').textContent='Salvo'}catch{$('#projectStatus').textContent='Não salvo'}renderWorkspace()}
function saveNow(){try{saveProject(localStorage,project);$('#projectStatus').textContent='Salvo';toast('Projeto salvo neste dispositivo.');renderRecent()}catch{showError('#builderError','Não foi possível salvar. Continue trabalhando e use Exportar projeto para não perder suas alterações.')}}
function exportNow(){try{const blob=new Blob([serializeProject(project)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${project.name.toLowerCase().replace(/[^a-z0-9]+/gi,'-')||'v30-projeto'}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),800);toast('Projeto exportado em JSON.')}catch(e){showError('#builderError',`Falha ao exportar: ${e.message}`)}}
function setTab(tab){$$('#projectTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));['files','screens','data','settings'].forEach(x=>$(`#${x}Panel`).classList.toggle('hidden',x!==tab))}
function setMobilePanel(panel){$$('[data-mobile-panel]').forEach(n=>n.classList.toggle('mobile-active',n.dataset.mobilePanel===panel));$$('[data-mobile-target]').forEach(b=>b.classList.toggle('active',b.dataset.mobileTarget===panel))}
function reset(){blueprint=null;project=null;activeScreen=null;$('#briefInput').value='';showError('#startError');renderRecent();showView('#startView')}

$('#buildBriefBtn').onclick=buildFromBrief;$('#confirmBuildBtn').onclick=confirmBuild;$('#editBriefBtn').onclick=()=>showView('#startView');$('#newProjectBtn').onclick=reset;$('#backHomeBtn').onclick=()=>{renderRecent();showView('#startView')};$('#saveProjectBtn').onclick=saveNow;$('#exportProjectBtn').onclick=exportNow;$('#sendChatBtn').onclick=()=>sendChat();$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}});$('#viewportDesktopBtn').onclick=()=>{$('#previewFrame').classList.remove('mobile');$('#viewportDesktopBtn').classList.add('active');$('#viewportMobileBtn').classList.remove('active')};$('#viewportMobileBtn').onclick=()=>{$('#previewFrame').classList.add('mobile');$('#viewportMobileBtn').classList.add('active');$('#viewportDesktopBtn').classList.remove('active')};$('#projectTabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)setTab(b.dataset.tab)});$$('[data-starter]').forEach(b=>b.onclick=()=>{$('#briefInput').value=b.dataset.starter;buildFromBrief()});$$('[data-command]').forEach(b=>b.onclick=()=>sendChat(b.dataset.command));$$('[data-mobile-target]').forEach(b=>b.onclick=()=>setMobilePanel(b.dataset.mobileTarget));$('#importI30Btn').onclick=()=>location.href='../';

renderRecent();setMobilePanel('preview');
const incoming=new URLSearchParams(location.search).get('brief');if(incoming){$('#briefInput').value=incoming;presentBlueprint(parseBrief(incoming))}
