(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.I30Generators=api;})(typeof window!=='undefined'?window:globalThis,function(){
  const safeIdea=value=>String(value||'').trim().slice(0,500);
  const now=()=>new Date().toISOString();
  const id=()=>`i30-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  const lines=sections=>sections.map(s=>`${s.heading}\n${s.content}`).join('\n\n');
  function result(type,idea,title,sections){return{id:id(),type,idea,title,sections,plainText:`${title}\n\n${lines(sections)}`,createdAt:now(),source:'local'};}
  const strategies={
    appIdea(idea){return result('appIdea',idea,`Projeto de aplicativo — ${idea}`,[
      {heading:'Nome do produto',content:`I30 sugere começar com um nome curto ligado ao principal benefício de “${idea}”. Valide o nome e domínio antes do lançamento.`},
      {heading:'Objetivo',content:`Transformar “${idea}” em um produto digital simples de usar, mobile-first e focado em resolver uma tarefa principal muito bem.`},
      {heading:'Público',content:`Pessoas ou equipes que hoje lidam com ${idea} usando mensagens, planilhas, papel, memória ou ferramentas separadas.`},
      {heading:'Telas',content:'1) Boas-vindas/login; 2) Dashboard; 3) Criar/registrar; 4) Detalhes; 5) Histórico; 6) Busca e filtros; 7) Perfil/configurações; 8) Plano/assinatura quando houver monetização.'},
      {heading:'Funcionalidades',content:`Fluxo principal para ${idea}; cadastro e edição; histórico; busca e filtros; indicadores no dashboard; notificações úteis; compartilhamento/exportação quando fizer sentido; estados vazios e mensagens de erro claras.`},
      {heading:'Dados e backend',content:'Usar Supabase para autenticação, banco PostgreSQL e regras de acesso. Estruturar tabelas para usuários, registros principais, histórico e configurações. Aplicar RLS para que cada usuário veja apenas o que tem permissão para acessar.'},
      {heading:'Visual',content:'Interface premium, limpa e responsiva. Mobile-first, cards arredondados, hierarquia visual forte, navegação simples, botões grandes para toque e contraste adequado. PWA instalável no celular e desktop.'},
      {heading:'Modelo de receita',content:'Começar com versão gratuita suficiente para demonstrar valor e plano Pro mensal para recursos avançados, automações, relatórios ou maior volume de uso.'},
      {heading:'Prompt para construir',content:`Crie uma PWA completa e responsiva para: ${idea}. O produto deve ser mobile-first, instalável, rápido e simples. Implemente autenticação com Supabase, PostgreSQL, RLS, dashboard, fluxo principal de cadastro/edição, detalhes, histórico, busca, filtros, perfil e configurações. Use componentes reutilizáveis, estados de loading/erro/vazio, persistência real, validação de formulários e experiência otimizada para celular. Organize o código para evolução futura e não use dados falsos como se fossem reais. Entregue uma primeira versão funcional que possa ser testada e evoluída.`},
      {heading:'Próxima evolução',content:'Depois do MVP: testar o fluxo principal com usuários reais, medir onde abandonam, corrigir fricções e só então adicionar IA, automações, integrações e recursos premium.'}
    ]);},
    post(idea){return result('post',idea,`Post para ${idea}`,[{heading:'Gancho',content:`Se você quer chamar atenção para ${idea}, comece mostrando o problema que o público já sente.`},{heading:'Legenda',content:`Apresente ${idea} de forma simples: qual problema resolve, para quem serve e qual transformação entrega. Mostre um benefício concreto e feche com uma pergunta que convide a pessoa a responder.`},{heading:'CTA',content:`Comente “QUERO” ou envie uma mensagem para saber mais sobre ${idea}.`},{heading:'Hashtags',content:'#ideias #conteudo #marketing #negocios #criacao'}]);},
    reels(idea){return result('reels',idea,`Roteiro de Reels/TikTok — ${idea}`,[{heading:'Gancho — 0 a 3s',content:`“E se eu te mostrasse uma forma melhor de pensar ${idea}?”`},{heading:'Cena 1',content:`Mostre o problema atual relacionado a ${idea}.`},{heading:'Cena 2',content:`Apresente como ${idea} pode resolver ou melhorar a situação.`},{heading:'Cena 3',content:'Mostre o benefício principal com exemplo visual.'},{heading:'Fechamento',content:`CTA: “Quer ver como eu transformaria ${idea} em algo real? Me chama.”`}]);},
    video(idea){return result('video',idea,`Pacote de produção de vídeo — ${idea}`,[{heading:'Formato',content:'Vídeo vertical 9:16, entre 25 e 40 segundos, ritmo rápido e visual premium.'},{heading:'Conceito',content:`Transformar ${idea} em uma narrativa curta de problema → possibilidade → resultado.`},{heading:'Cenas',content:`1) Gancho; 2) contexto de ${idea}; 3) solução; 4) benefício; 5) CTA.`},{heading:'Prompt de render',content:`Crie um vídeo vertical premium sobre ${idea}, com estética tecnológica elegante, cortes rápidos e CTA forte.`},{heading:'Observação',content:'Este é um pacote de produção de vídeo. Nenhum MP4 foi renderizado nesta versão local do I30.'}]);},
    prompt(idea){return result('prompt',idea,`Prompt completo — ${idea}`,[{heading:'Objetivo',content:`Ajude a transformar ${idea} em uma solução clara, prática e executável.`},{heading:'Contexto',content:`Analise “${idea}” considerando público, problema, proposta de valor, diferenciais e execução.`},{heading:'Instruções',content:'Organize em diagnóstico, estratégia, passos práticos, riscos, melhorias e próximos testes.'},{heading:'Formato de saída',content:'Use títulos curtos, ações priorizadas e exemplos aplicáveis.'}]);},
    brand(idea){return result('brand',idea,`Direções de nome e marca — ${idea}`,[{heading:'Direção 1',content:`Nome curto inspirado no benefício de ${idea}.`},{heading:'Direção 2',content:`Nome premium e memorável para ${idea}.`},{heading:'Posicionamento',content:`Comunicar ${idea} como solução moderna, direta e fácil de entender.`}]);},
    offer(idea){return result('offer',idea,`Estrutura de oferta — ${idea}`,[{heading:'Público',content:`Pessoas ou empresas com o problema ligado a ${idea}.`},{heading:'Promessa',content:`Transformar ${idea} em um caminho mais simples e executável.`},{heading:'Benefícios',content:'Clareza, menos tempo perdido, execução guiada e próximos passos.'},{heading:'CTA',content:`Comece agora com ${idea}.`}]);},
    ad(idea){return result('ad',idea,`Anúncio — ${idea}`,[{heading:'Headline',content:`Sua ideia sobre ${idea} não precisa ficar parada.`},{heading:'Corpo',content:`Transforme ${idea} em uma ação concreta sem complicar o processo.`},{heading:'CTA',content:'Quero transformar minha ideia'}]);},
    salesPage(idea){return result('salesPage',idea,`Página de venda — ${idea}`,[{heading:'Hero',content:`Título direto sobre o principal resultado de ${idea}, subtítulo e CTA.`},{heading:'Problema',content:`Mostre por que a forma atual de lidar com ${idea} custa tempo ou oportunidade.`},{heading:'Solução',content:`Explique como ${idea} será entregue.`},{heading:'Benefícios',content:'Liste de 3 a 5 ganhos concretos.'},{heading:'Oferta e CTA',content:'Entregáveis, condição e CTA único.'}]);},
    contentPlan(idea){return result('contentPlan',idea,`Plano de conteúdo — ${idea}`,[{heading:'Pilares',content:`Educação, bastidores, prova, opinião e oferta sobre ${idea}.`},{heading:'7 dias',content:`Problema; dica; bastidor; erro comum; demonstração; caso; oferta ligada a ${idea}.`},{heading:'Formatos',content:'Reels, carrossel, post, stories e vídeo.'}]);},
    launchStrategy(idea){return result('launchStrategy',idea,`Estratégia de lançamento — ${idea}`,[{heading:'Objetivo',content:`Gerar atenção, validação e primeiras conversas para ${idea}.`},{heading:'Pré-lançamento',content:'Mostrar problema, bastidores e construção.'},{heading:'Lançamento',content:`Apresentar ${idea} com demonstração e CTA único.`},{heading:'Métricas',content:'Cliques, respostas, leads, demonstrações e conversão.'}]);}
  };
  function generateCreation({type,idea,context={}}){const clean=safeIdea(idea);if(!clean)throw new Error('Descreva sua ideia antes de gerar.');if(type==='saas30')throw new Error('O módulo 30 ideias de SaaS usa o motor original do I30.');const fn=strategies[type];if(!fn)throw new Error('Tipo de criação desconhecido.');return fn(clean,context);}
  return {generateCreation};
});
