(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.I30Generators=api;})(typeof window!=='undefined'?window:globalThis,function(){
  const safeIdea=value=>String(value||'').trim().slice(0,500);
  const now=()=>new Date().toISOString();
  const id=()=>`i30-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
  const lines=sections=>sections.map(s=>`${s.heading}\n${s.content}`).join('\n\n');
  function result(type,idea,title,sections){return{id:id(),type,idea,title,sections,plainText:`${title}\n\n${lines(sections)}`,createdAt:now(),source:'local'};}
  const strategies={
    post(idea){return result('post',idea,`Post para ${idea}`,[{heading:'Gancho',content:`Se você quer chamar atenção para ${idea}, comece mostrando o problema que o público já sente.`},{heading:'Legenda',content:`Apresente ${idea} de forma simples: qual problema resolve, para quem serve e qual transformação entrega. Mostre um benefício concreto e feche com uma pergunta que convide a pessoa a responder.`},{heading:'CTA',content:`Comente “QUERO” ou envie uma mensagem para saber mais sobre ${idea}.`},{heading:'Hashtags',content:'#ideias #conteudo #marketing #negocios #criacao'}]);},
    reels(idea){return result('reels',idea,`Roteiro de Reels/TikTok — ${idea}`,[{heading:'Gancho — 0 a 3s',content:`“E se eu te mostrasse uma forma melhor de pensar ${idea}?”`},{heading:'Cena 1',content:`Mostre o problema atual relacionado a ${idea}. Texto na tela: “O problema que quase ninguém percebe”.`},{heading:'Cena 2',content:`Apresente a ideia central e explique em uma frase como ${idea} pode resolver ou melhorar a situação.`},{heading:'Cena 3',content:'Mostre o benefício principal em linguagem simples, com exemplo visual ou comparação.'},{heading:'Fechamento',content:`CTA: “Quer ver como eu transformaria ${idea} em algo real? Me chama.”`},{heading:'Legenda',content:`Uma ideia só ganha valor quando vira execução. Hoje: ${idea}.`}]);},
    video(idea){return result('video',idea,`Pacote de produção de vídeo — ${idea}`,[{heading:'Formato',content:'Vídeo vertical 9:16, entre 25 e 40 segundos, ritmo rápido e visual premium.'},{heading:'Conceito',content:`Transformar ${idea} em uma narrativa curta de problema → possibilidade → resultado.`},{heading:'Cenas',content:`1) Gancho visual; 2) contexto de ${idea}; 3) demonstração da solução; 4) benefício; 5) CTA final.`},{heading:'Narração',content:`“Toda grande execução começa com uma ideia. ${idea} pode sair do papel quando existe clareza, estrutura e ação.”`},{heading:'Trilha / clima',content:'Tecnologia, progresso e energia crescente, sem competir com a voz.'},{heading:'Prompt de render',content:`Crie um vídeo vertical premium sobre ${idea}, com estética tecnológica elegante, cortes rápidos, tipografia limpa, cenas coerentes com o tema e encerramento com CTA forte.`},{heading:'Observação',content:'Este é um pacote de produção de vídeo. Nenhum MP4 foi renderizado nesta versão local do I30.'}]);},
    prompt(idea){return result('prompt',idea,`Prompt completo — ${idea}`,[{heading:'Objetivo',content:`Ajude a transformar ${idea} em uma solução clara, prática e executável.`},{heading:'Contexto',content:`Analise o tema “${idea}” considerando público, problema, proposta de valor, diferenciais e execução.`},{heading:'Instruções',content:'Organize a resposta em diagnóstico, estratégia, passos práticos, riscos, melhorias e próximos testes.'},{heading:'Restrições',content:'Não invente dados de mercado. Diferencie fatos, hipóteses e recomendações.'},{heading:'Formato de saída',content:'Use títulos curtos, ações priorizadas e exemplos diretamente aplicáveis.'}]);},
    brand(idea){return result('brand',idea,`Direções de nome e marca — ${idea}`,[{heading:'Direção 1',content:`Nome curto inspirado em velocidade e clareza para ${idea}. Slogan: “Da ideia ao resultado.”`},{heading:'Direção 2',content:`Nome com sensação premium e autoridade para ${idea}. Slogan: “Criado para avançar.”`},{heading:'Direção 3',content:`Nome simples e memorável ligado ao benefício principal de ${idea}. Slogan: “Menos complexidade. Mais resultado.”`},{heading:'Posicionamento',content:`A marca deve comunicar ${idea} como uma solução moderna, direta e fácil de entender em poucos segundos.`}]);},
    offer(idea){return result('offer',idea,`Estrutura de oferta — ${idea}`,[{heading:'Público',content:`Pessoas ou empresas que já convivem com o problema ligado a ${idea}.`},{heading:'Problema',content:`Falta de clareza, processo ou solução prática para avançar em ${idea}.`},{heading:'Promessa',content:`Transformar ${idea} em um caminho mais simples, organizado e executável.`},{heading:'Benefícios',content:'Mais clareza, menos tempo perdido, execução guiada e visão de próximos passos.'},{heading:'Objeções',content:'“Vai funcionar para mim?”, “é complicado?”, “quanto tempo leva?” — responda com demonstração, simplicidade e prova.'},{heading:'CTA',content:`Comece agora com ${idea} e veja o primeiro resultado antes de assumir um compromisso maior.`}]);},
    ad(idea){return result('ad',idea,`Anúncio — ${idea}`,[{heading:'Headline',content:`Sua ideia sobre ${idea} não precisa ficar parada.`},{heading:'Corpo',content:`Se ${idea} é algo que você quer tirar do papel, comece com uma estrutura clara. Veja como transformar a ideia em uma ação concreta sem complicar o processo.`},{heading:'CTA',content:'Quero transformar minha ideia'},{heading:'Variações',content:`1) “Comece ${idea} hoje.” 2) “Sua próxima ideia pode virar produto.” 3) “Pare de apenas pensar em ${idea}.”`}]);},
    salesPage(idea){return result('salesPage',idea,`Página de venda — ${idea}`,[{heading:'Hero',content:`Título direto sobre o principal resultado de ${idea}, subtítulo com público e CTA principal.`},{heading:'Problema',content:`Mostre por que a forma atual de lidar com ${idea} custa tempo, dinheiro ou oportunidade.`},{heading:'Solução',content:`Explique como ${idea} será entregue e por que o processo é mais simples.`},{heading:'Benefícios',content:'Liste de 3 a 5 ganhos concretos e fáceis de visualizar.'},{heading:'Prova',content:'Inclua demonstrações, casos reais, números verificáveis ou depoimentos quando existirem.'},{heading:'Oferta',content:'Plano, entregáveis, preço/condição quando definido e redução de risco.'},{heading:'FAQ e CTA',content:'Responda objeções principais e repita um CTA único e claro.'}]);},
    appIdea(idea){return result('appIdea',idea,`Blueprint de aplicativo — ${idea}`,[{heading:'Problema',content:`O app deve resolver a principal fricção relacionada a ${idea} sem tentar atender tudo na primeira versão.`},{heading:'Público',content:`Usuários que hoje resolvem ${idea} com planilhas, mensagens, memória ou várias ferramentas separadas.`},{heading:'Proposta de valor',content:`Centralizar e simplificar ${idea} em uma experiência rápida, mobile-first e fácil de repetir.`},{heading:'MVP',content:'Login opcional, dashboard, fluxo principal, histórico, busca/filtros e configurações essenciais.'},{heading:'Modelo de receita',content:'Freemium com plano Pro ou assinatura mensal, dependendo da frequência de uso e valor entregue.'},{heading:'Prompt técnico inicial',content:`Crie uma PWA responsiva para ${idea}, mobile-first, com fluxo principal simples, persistência segura, estados vazios, histórico e arquitetura pronta para backend.`}]);},
    contentPlan(idea){return result('contentPlan',idea,`Plano de conteúdo — ${idea}`,[{heading:'Pilares',content:`1) Educação sobre ${idea}; 2) bastidores; 3) prova/resultado; 4) opinião; 5) oferta.`},{heading:'7 dias',content:`Dia 1 gancho/problema; Dia 2 dica prática; Dia 3 bastidor; Dia 4 erro comum; Dia 5 demonstração; Dia 6 história/caso; Dia 7 oferta ligada a ${idea}.`},{heading:'Formatos',content:'Alternar Reels, carrossel, post curto, stories e vídeo de resposta.'},{heading:'CTA',content:'Use um CTA por conteúdo: comentar, salvar, compartilhar, responder ou chamar no direct.'}]);},
    launchStrategy(idea){return result('launchStrategy',idea,`Estratégia de lançamento — ${idea}`,[{heading:'Objetivo',content:`Gerar atenção, validação e primeiras conversas comerciais para ${idea}.`},{heading:'Pré-lançamento',content:'Mostrar problema, bastidores, construção e pequenos aprendizados antes de apresentar a oferta.'},{heading:'Lançamento',content:`Apresentar ${idea} com demonstração clara, CTA único e janela de ação definida.`},{heading:'Canais',content:'Instagram/TikTok para alcance, YouTube para profundidade, WhatsApp/e-mail para conversão.'},{heading:'Métricas',content:'Visualizações qualificadas, cliques, respostas, leads, demonstrações e conversão.'},{heading:'Próximos passos',content:'Reunir feedback, corrigir objeções recorrentes e relançar com mensagem mais precisa.'}]);}
  };
  function generateCreation({type,idea,context={}}){const clean=safeIdea(idea);if(!clean)throw new Error('Descreva sua ideia antes de gerar.');if(type==='saas30')throw new Error('O módulo 30 ideias de SaaS usa o motor original do I30.');const fn=strategies[type];if(!fn)throw new Error('Tipo de criação desconhecido.');return fn(clean,context);}
  return {generateCreation};
});
